<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\Search' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/Search.php';

return $this->privates['App\\Service\\Search'] = new \App\Service\Search($this);
