fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "wiwattcontact@gmail.com"	
        sender_name: "wiwattcontact@gmail.com"	
    registration:
        confirmation:
            enabled: true