swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    disable_delivery: false
    transport: gmail
    username: wiwattcontact@gmail.com
    password: 9SzU@d4atdtXF4L
    host: localhost
    port: 465
    encryption: ssl
    auth-mode: login
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false