<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vehicle extends \App\Entity\Vehicle implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'brand', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'model', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'seatNumber', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'maxSpeed', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'weight', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'power', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'autonomy', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'dayCost', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'pictures', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'zipCode', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'adress', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'longitude', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'latitude', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'dates', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'bookings'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'brand', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'model', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'seatNumber', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'maxSpeed', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'weight', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'power', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'autonomy', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'dayCost', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'pictures', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'zipCode', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'adress', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'longitude', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'latitude', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'dates', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'bookings'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vehicle $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', []);

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand(string $brand): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', [$brand]);

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getModel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModel', []);

        return parent::getModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setModel(string $model): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModel', [$model]);

        return parent::setModel($model);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeatNumber(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeatNumber', []);

        return parent::getSeatNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeatNumber(int $seatNumber): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeatNumber', [$seatNumber]);

        return parent::setSeatNumber($seatNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxSpeed(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxSpeed', []);

        return parent::getMaxSpeed();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxSpeed(int $maxSpeed): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxSpeed', [$maxSpeed]);

        return parent::setMaxSpeed($maxSpeed);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeight(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeight', []);

        return parent::getWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeight(int $weight): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeight', [$weight]);

        return parent::setWeight($weight);
    }

    /**
     * {@inheritDoc}
     */
    public function getPower(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPower', []);

        return parent::getPower();
    }

    /**
     * {@inheritDoc}
     */
    public function setPower(int $power): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPower', [$power]);

        return parent::setPower($power);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutonomy(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutonomy', []);

        return parent::getAutonomy();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutonomy(int $autonomy): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutonomy', [$autonomy]);

        return parent::setAutonomy($autonomy);
    }

    /**
     * {@inheritDoc}
     */
    public function getDayCost(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDayCost', []);

        return parent::getDayCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setDayCost(int $dayCost): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDayCost', [$dayCost]);

        return parent::setDayCost($dayCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(bool $status): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', []);

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode(int $zipCode): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', [$zipCode]);

        return parent::setZipCode($zipCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(string $city): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdress', []);

        return parent::getAdress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdress(string $adress): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdress', [$adress]);

        return parent::setAdress($adress);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude(float $longitude): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude(float $latitude): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latitude]);

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(?\DateTimeInterface $updatedAt): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPictures(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPictures', []);

        return parent::getPictures();
    }

    /**
     * {@inheritDoc}
     */
    public function addPicture(\App\Entity\Picture $picture): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPicture', [$picture]);

        return parent::addPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function removePicture(\App\Entity\Picture $picture): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePicture', [$picture]);

        return parent::removePicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?\App\Entity\Type
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(?\App\Entity\Type $type): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getDates(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDates', []);

        return parent::getDates();
    }

    /**
     * {@inheritDoc}
     */
    public function addDate(\App\Entity\Date $date): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDate', [$date]);

        return parent::addDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDate(\App\Entity\Date $date): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDate', [$date]);

        return parent::removeDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookings', []);

        return parent::getBookings();
    }

    /**
     * {@inheritDoc}
     */
    public function addBooking(\App\Entity\Booking $booking): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBooking', [$booking]);

        return parent::addBooking($booking);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBooking(\App\Entity\Booking $booking): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBooking', [$booking]);

        return parent::removeBooking($booking);
    }

}
