<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xW.u.b0' shared service.

return $this->privates['.service_locator.xW.u.b0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'fileUploadManager' => ['privates', 'App\\Service\\FileUploadManager', 'getFileUploadManagerService.php', true],
], [
    'encoder' => '?',
    'fileUploadManager' => 'App\\Service\\FileUploadManager',
]);
