<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3Kb.qT.' shared service.

return $this->privates['.service_locator.3Kb.qT.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'booking' => ['privates', '.errored..service_locator.3Kb.qT..App\\Entity\\Booking', NULL, 'Cannot autowire service ".service_locator.3Kb.qT.": it references class "App\\Entity\\Booking" but no such service exists.'],
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'mailer' => ['services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService.php', true],
], [
    'booking' => 'App\\Entity\\Booking',
    'em' => '?',
    'mailer' => '?',
]);
