<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VA7hhhg' shared service.

return $this->privates['.service_locator.VA7hhhg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'search' => ['privates', 'App\\Service\\Search', 'getSearchService.php', true],
], [
    'search' => 'App\\Service\\Search',
]);
