<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXN13XqE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXN13XqE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXN13XqE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXN13XqE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXN13XqE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XN13XqE',
    'container.build_id' => '7fe27aef',
    'container.build_time' => 1578930674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXN13XqE');
