<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWJuXoQU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWJuXoQU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWJuXoQU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWJuXoQU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWJuXoQU\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WJuXoQU',
    'container.build_id' => '10119345',
    'container.build_time' => 1589037845,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWJuXoQU');
